export const UPLOAD_COMPLETED = 'UPLOAD_COMPLETED'
export const LAWYER_APPROVED = 'LAWYER_APPROVED'
export const TASK_COMPLETED = 'TASK_COMPLETED'
export const TASK_REVISION_REQUIRED = 'TASK_REVISION_REQUIRED'
export const MATERIAL_ADDED = 'MATERIAL_ADDED'
export const FINALIZED = 'FINALIZED'

export type MatterEventType =
    | typeof UPLOAD_COMPLETED
    | typeof LAWYER_APPROVED
    | typeof TASK_COMPLETED
    | typeof TASK_REVISION_REQUIRED
    | typeof MATERIAL_ADDED
    | typeof FINALIZED

export default {
    UPLOAD_COMPLETED,
    LAWYER_APPROVED,
    TASK_COMPLETED,
    TASK_REVISION_REQUIRED,
    MATERIAL_ADDED,
    FINALIZED,
}
